# A part of NonVisual Desktop Access (NVDA)
# This file is covered by the GNU General Public License.
# See the file COPYING for more details.


from collections.abc import Iterable
from typing import Callable

import speech
from speech import sayAll
from speech.commands import BreakCommand
from speech.types import SpeechSequence

from .pipeline.settings import get_effective_pipeline_settings


def _wrap_get_text_info_speech_with_sayall_break(
		getTextInfoSpeech: Callable[..., Iterable[SpeechSequence]],
) -> Callable[..., Iterable[SpeechSequence]]:
	"""Add the configured pause after each speech sequence generated by Say All."""
	def getTextInfoSpeechWithSayAllBreak(*args, **kwargs):
		yield from getTextInfoSpeech(*args, **kwargs)

		waitFactor = get_effective_pipeline_settings().scaled_sayall_wait()
		if waitFactor > 0:
			yield [BreakCommand(waitFactor + 100)]

	return getTextInfoSpeechWithSayAllBreak


def patch():
	sayAll.initialize(
		speech.speech.speak,
		speech.speech.speakObject,
		_wrap_get_text_info_speech_with_sayall_break(speech.speech.getTextInfoSpeech),
		speech.speech.SpeakTextInfoState,
	)


def unpatch():
	sayAll.initialize(
		speech.speech.speak,
		speech.speech.speakObject,
		speech.speech.getTextInfoSpeech,
		speech.speech.SpeakTextInfoState,
	)
